---
fmg_host: 34.154.60.76:14006
fmg_user: admin
fmg_password: fortinet
fmg_adom: CustomerC

postman_collection: /Users/dperets/git/postman_collections/Deployment_Guide_SDWAN_7_2_x.postman.json

fgfm_ip: 192.168.0.15
fgt_user: admin
fgt_password: fortinet

sites:
  site1-1:
    ip: 34.154.60.76
    port: 11007
    latitude: 44.837789
    longitude: -0.57918
    address: Bordeaux, France
  site1-2:
    ip: 34.154.60.76
    port: 11008
    latitude: 44.494887
    longitude: 11.3426163
    address: Bologna, Italy
  site2-1:
    ip: 34.154.60.76
    port: 11011
    latitude: 44.494887
    longitude: 11.3426163
    address: Belgrade, Serbia
  site1-H1:
    ip: 34.154.60.76
    port: 11009
    latitude: 48.856614
    longitude: 2.3522219
    address: Paris, France
  site1-H2:
    ip: 34.154.60.76
    port: 11010
    latitude: 52.3675734
    longitude: 4.9041389
    address: Amsterdam, The Netherlands
  site2-H1:
    ip: 34.154.60.76
    port: 11012
    latitude: 52.3675734
    longitude: 4.9041389
    address: Warsaw, Poland

tasks:
  - name: Create Foundation
    type: postman
    folder: Foundation
  - name: Import Project Template
    type: cli_templates
    src: tenants/CustomerC/Project.dualreg.j2
    rename: Project
  - name: Import Jinja CLI Templates
    type: cli_templates
    src: /Users/dperets/git/sdwan-advpn-reference/dynamic-bgp-on-lo/*.j2
  - name: Create CLI Template Groups
    type: postman
    folder: Create CLI Template Groups
  - name: Create Template Groups
    type: postman
    folder: Create Template Groups
  - name: Create Device Blueprints
    type: postman
    folder: Device Blueprints
  - name: Create Model Devices
    type: model_devices
    src: tenants/CustomerC/inventory.CustomerC.csv    
  - name: Install Model Devices (Staging)
    type: postman
    folder: Staging
  - name: Onboard Devices
    type: onboard
    src: tenants/CustomerC/inventory.CustomerC.csv
